#!/usr/bin/env ruby
require_relative 'terminal'

#ls
#Need to change permissions when first created $chmod 755 run.sh
#To run on double click:
# chmod a+x yourscriptname
# change the default application to terminal in finder
# cd Desktop/myDSEC 
# ruby terminal.rb

